---
apiVersion: v1
kind: Namespace
metadata:
  name: psg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psg
  namespace: psg
  labels:
    app: &nom psg
    env: prod
    ver: "5"
spec:
  revisionHistoryLimit: 10
  replicas: 3
  selector:
    matchLabels:
      app: *nom
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: *nom
        env: prod
        ver: "6"
    spec:
      containers:
      - image: supskifun/web:go-1.15.8-arm
        name: *nom
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "8Mi"
          limits:
            cpu: "1000m"
            memory: "32Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
